version: 0.2

env:
  variables:
    S3_BUCKET: to-do-list-frontend
    LAMBDA_BASE_PATH: lambda

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing AWS CLI..."
      - npm install -g aws-cli zip

  build:
    commands:
      - echo "Zipping and uploading Lambda functions..."

      # Loop through Lambda directories and zip/upload each one
      - for dir in Lambda/*/ ; do
          fname=$(basename $dir);
          cd $dir;
          zip -r function.zip .;
          aws s3 cp function.zip s3://$S3_BUCKET/$LAMBDA_BASE_PATH/$fname/function.zip;
          cd -;
        done

  post_build:
    commands:
      - echo "Updating Lambda functions..."

      - aws lambda update-function-code --function-name cognito_login --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/cognito_login/function.zip
      - aws lambda update-function-code --function-name Cognito_register --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/Cognito_register/function.zip
      - aws lambda update-function-code --function-name complete_task_private --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/complete_task_private/function.zip
      - aws lambda update-function-code --function-name complete_task_public --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/complete_task_public/function.zip
      - aws lambda update-function-code --function-name create_tasks_public --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/Create_Tasks_Private/function.zip
      - aws lambda update-function-code --function-name create_tasks --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/create_tasks/function.zip
      - aws lambda update-function-code --function-name delete_task_private --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/delete_task_private/function.zip
      - aws lambda update-function-code --function-name delete_tasks_public --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/delete_tasks_public/function.zip
      - aws lambda update-function-code --function-name delete_user_private --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/delete_user_private/function.zip
      - aws lambda update-function-code --function-name delete_user_public --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/delete_user_public/function.zip
      - aws lambda update-function-code --function-name get_quotes --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/get_quotes/function.zip
      - aws lambda update-function-code --function-name get_tasks_private --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/get_tasks_private/function.zip
      - aws lambda update-function-code --function-name get_tasks_public --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/get_tasks_public/function.zip
      - aws lambda update-function-code --function-name update_task_private --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/update_task_private/function.zip
      - aws lambda update-function-code --function-name update_task_public --s3-bucket $S3_BUCKET --s3-key $LAMBDA_BASE_PATH/update_task_public/function.zip
