version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing...

  build:
    commands:
      - echo Build step...

artifacts:
  files:
    - '**/*'
  base-directory: .
