version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g lighthouse pa11y newman
      - npm install

  build:
    commands:
      # ✅ Run Accessibility Tests (Lighthouse & Pa11y)
      - echo "Running Pa11y Accessibility Test..."
      - pa11y https://to-do-list-frontend.s3.us-east-1.amazonaws.com/static_files/index.html --json > pa11y_results.json

  post_build:
    commands:
      - echo "Tests Completed!"
      - cat pa11y_results.json
